#!/bin/bash

# Made by hosua
# github.com/hosua

LIST_HEIGHT=10

SORT_BY="-%cpu"
FMT="pid,%cpu,exe"

ps -eo "$FMT" --sort "$SORT_BY" | \
  tail -n +2 | \
  dmenu -l $LIST_HEIGHT -p "Kill" | \
  cut -d' ' -f1 | \
  xargs kill -9

