#!/bin/bash

# Made by hosua
# github.com/hosua

LIST_HEIGHT=20

SORT_BY="-rss"
FMT="pid,%cpu,rss,exe"

ps -eo "$FMT" --sort "$SORT_BY" |
  awk '{m=$3/1024; $3 = (m>1000 ? sprintf("%.2fGB", m/1024) : sprintf("%.2fMB", m)); print}' |
  column -t |
  tail -n +2 |
  dmenu -l $LIST_HEIGHT -p "Kill" |
  awk '{print $1}' |
  xargs kill -9
