[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0Nfile:///mnt/HDD2/Downloads/Torrents/Shows/The.Wire.S01.1080p.BluRay.x265-RARBG)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\v\xf4\0\0\x2)\0\0\xe\xfb\0\0\x4\x33\0\0\v\xf5\0\0\x2>\0\0\xe\xfa\0\0\x4\x32\0\0\0\x1\0\0\0\0\a\x80\0\0\v\xf5\0\0\x2>\0\0\xe\xfa\0\0\x4\x32)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(774 427)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\xf\0\0\0\0\x16\0\0\x14\xf2\0\0\x2\xb1\0\0\xf\x1\0\0\0+\0\0\x14\xf1\0\0\x2\xb0\0\0\0\0\0\0\0\0\a\x80\0\0\xf\x1\0\0\0+\0\0\x14\xf1\0\0\x2\xb0)

[RecentsMRL]
list=file:///home/hoswoo/Videos/2026-03-31%2016-36-45.mp4, file:///home/hoswoo/Videos/2026-03-30%2012-20-47.mp4, file:///home/hoswoo/Downloads/wellstat/Meeting%20Recordings/001-DR_Enrollments_Meeting-AL-SA.mp4, file:///home/hoswoo/Downloads/wellstat/Meeting%20Recordings/Call%20with%20Josh%20and%201%20other-20260327_101501-Meeting%20Recording.mp4, file:///run/media/hoswoo/1234-5678/monero-storage/wallets/hosua/hosua, file:///mnt/HDD2/Downloads/Torrents/Shows/The.Wire.S01.1080p.BluRay.x265-RARBG/The.Wire.S01E01.1080p.BluRay.x265-RARBG.mp4
times=0, 0, 0, 1535900, 8584, 0
